/*
I. SWITCH
    Sự dụng switch để chọn 1 trong nhiều khối mã sẽ đc thục thi
    * CÁCH THỨC HOẠT DỘNG CỦA CHÚNG:- Biểu thức của SWITCH được đánh giá mỗi lần
                                    - Giá trị biểu thức được đem so sánh với từng CASE
                                    - Nếu giá trị khớp khối mã của giá trị đó sẽ được thực thi
II. BREAK
    BREAK Là thoát khỏi chương trình 
III. default:
    Chỉ định một khối mã chạy nếu không có CASE nào khớp

*/